session_name: Commencis
windows:
- layout: cbc1,158x66,0,0,4
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: zsh
  start_directory: /Users/ozgumusy/work/Pegasus-Dev
  window_name: Pegasus Dev
- layout: cbc2,158x66,0,0,5
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: zsh
  start_directory: /Users/ozgumusy/work/Pegasus-Poc
  window_name: Pegasus Poc
- focus: 'true'
  layout: cbc3,158x66,0,0,6
  options: {}
  panes:
  - focus: 'true'
    shell_command: zsh
  start_directory: /Users/ozgumusy
  window_name: zsh
