#!/usr/bin/env sh

NOTES_PATH="/Users/yigitozgumus/Google Drive/Personal/Obsidian/Second Brain/"

cd "$NOTES_PATH"

CHANGES_EXIST="$(git status --porcelain | wc -l)"

if [ "$CHANGES_EIST" -eq 0 ]; then
    exit 0
fi

git pull
git add .
git commit -q -m "Last Sync: $(date "+%d-%m-%Y %H:%M:%S")"
git push -q
