# kurokula
[colors]
foreground = "#ddd0c4"
background = "#141515"
cursor_bg = "#702420"
cursor_border = "#702420"
cursor_fg = "#fefbf3"
selection_bg = "#515151"
selection_fg = "#ffc663"

ansi = ["#333333","#b66056","#85b1a9","#dbbb43","#6890d7","#887aa3","#837369","#ddd0c4"]
brights = ["#515151","#ffc663","#c1ffae","#fff700","#a1d9ff","#a994ff","#f9cfb9","#ffffff"]
