# Oxocarbon
[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#393939"
selection_fg = "#161616"

ansi = ["#161616","#3ddbd9","#33b1ff","#ee5396","#42be65","#be95ff","#ff7eb6","#f2f4f8"]
brights = ["#585858","#3ddbd9","#33b1ff","#ee5396","#42be65","#be95ff","#ff7eb6","#f2f4f8"]
