schemes:
  light: &light
    primary:
      background: "#fef9ec"
      foreground: "#6d727e"
    cursor:
      text: "#fef9ec"
      cursor: "#6d727e"
    normal:
      black: "#c5c1b4"
      red: "#e75c58"
      green: "#00a250"
      yellow: "#a08a00"
      blue: "#208ffb"
      magenta: "#d160c4"
      cyan: "#00a4c1"
      white: "#3e424d"
    bright:
      black: "#a1a6b2"
      red: "#b22b31"
      green: "#007427"
      yellow: "#715f00"
      blue: "#0065ca"
      magenta: "#a03196"
      cyan: "#007693"
      white: "#282c36"
  dark: &dark # Default colors
    primary:
      background: "0x1b182c"
      foreground: "0xcbe3e7"

    # Normal colors
    normal:
      black: "0x100e23"
      red: "0xff8080"
      green: "0x95ffa4"
      yellow: "0xffe9aa"
      blue: "0x91ddff"
      magenta: "0xc991e1"
      cyan: "0xaaffe4"
      white: "0xcbe3e7"

    # Bright colors
    bright:
      black: "0x565575"
      red: "0xff5458"
      green: "0x62d196"
      yellow: "0xffb378"
      blue: "0x65b2ff"
      magenta: "0x906cff"
      cyan: "0x63f2f1"
      white: "0xa6b3cc"
colors: *dark
