# alacritty color scheme

schemes:
  gruvbox_light: &gruvbox_light
    primary:
      background: "#f1efee"
      foreground: "#68615e"
    cursor:
      text: "#f1efee"
      cursor: "#68615e"
    normal:
      black: "#1b1918"
      red: "#f22c40"
      green: "#5ab738"
      yellow: "#d5911a"
      blue: "#407ee7"
      magenta: "#6666ea"
      cyan: "#00ad9c"
      white: "#a8a19f"
    bright:
      black: "#766e6b"
      red: "#f22c40"
      green: "#5ab738"
      yellow: "#d5911a"
      blue: "#407ee7"
      magenta: "#6666ea"
      cyan: "#00ad9c"
      white: "#f1efee"
  gruvbox_dark: &gruvbox_dark
    # Default colors
    primary:
      background: "#000000"
      foreground: "#ffffff"
    cursor:
      text: "#000000"
      cursor: "#ffffff"
    normal:
      black: "#252525"
      red: "#ef6769"
      green: "#a6e22e"
      yellow: "#fd971f"
      blue: "#6495ed"
      magenta: "#deb887"
      cyan: "#b0c4de"
      white: "#dbdcdc"
    bright:
      black: "#454545"
      red: "#fc7ca5"
      green: "#b6e354"
      yellow: "#fd971f"
      blue: "#87ceeb"
      magenta: "#996600"
      cyan: "#87ceeb"
      white: "#fdfdfd"

colors: *gruvbox_dark

