# alacritty color scheme

schemes:
  gruvbox_light: &gruvbox_light
    # Default colors
# Default Colors
    primary:
      background: '#f1f1f1'
      foreground: '#424242'
  # Normal colors
    normal:
      black:   '#212121'
      red:     '#c30771'
      green:   '#10a778'
      yellow:  '#a89c14'
      blue:    '#008ec4'
      magenta: '#523c79'
      cyan:    '#20a5ba'
      white:   '#e0e0e0'
  # Bright colors
    bright:
      black:   '#212121'
      red:     '#fb007a'
      green:   '#5fd7af'
      yellow:  '#f3e430'
      blue:    '#20bbfc'
      magenta: '#6855de'
      cyan:    '#4fb8cc'
      white:   '#f1f1f1'
  gruvbox_dark: &gruvbox_dark
    # Default colors
    primary:
      background: '#1d2021' # hard contrast
      # background: '0x282828' # normal contrast
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

colors: *gruvbox_dark

