schemes:
  light: &light
    primary:
      background: "#fef9ec"
      foreground: "#6d727e"
    cursor:
      text: "#fef9ec"
      cursor: "#6d727e"
    normal:
      black: "#c5c1b4"
      red: "#e75c58"
      green: "#00a250"
      yellow: "#a08a00"
      blue: "#208ffb"
      magenta: "#d160c4"
      cyan: "#00a4c1"
      white: "#3e424d"
    bright:
      black: "#a1a6b2"
      red: "#b22b31"
      green: "#007427"
      yellow: "#715f00"
      blue: "#0065ca"
      magenta: "#a03196"
      cyan: "#007693"
      white: "#282c36"
  dark: &dark # Default colors
    primary:
      background: "#000000"
      foreground: "#ffffff"
    cursor:
      text: "#000000"
      cursor: "#ffffff"
    normal:
      black: "#666666"
      red: "#cc6666"
      green: "#66cc99"
      yellow: "#cc9966"
      blue: "#6699cc"
      magenta: "#cc6699"
      cyan: "#66cccc"
      white: "#cccccc"
    bright:
      black: "#999999"
      red: "#ff9999"
      green: "#99ffcc"
      yellow: "#ffcc99"
      blue: "#99ccff"
      magenta: "#ff99cc"
      cyan: "#99ffff"
      white: "#ffffff"

catpuccin: &catpuccin # Default colors
  primary:
    background: "0x1E1D2F"
    foreground: "0xD9E0EE"

  cursor:
    text: "0x1E1D2F"
    cursor: "0xF5E0DC"

  # Normal colors
  normal:
    black: "0x6E6C7E"
    red: "0xF28FAD"
    green: "0xABE9B3"
    yellow: "0xFAE3B0"
    blue: "0x96CDFB"
    magenta: "0xF5C2E7"
    cyan: "0x89DCEB"
    white: "0xD9E0EE"

  # Bright colors
  bright:
    black: "0x988BA2"
    red: "0xF28FAD"
    green: "0xABE9B3"
    yellow: "0xFAE3B0"
    blue: "0x96CDFB"
    magenta: "0xF5C2E7"
    cyan: "0x89DCEB"
    white: "0xD9E0EE"

  indexed_colors:
    - { index: 16, color: "0xF8BD96" }
    - { index: 17, color: "0xF5E0DC" }

github: &github # Default colors
  primary:
    background: "0x0d1117"
    foreground: "0xb3b1ad"

  # Normal colors
  normal:
    black: "0x484f58"
    red: "0xff7b72"
    green: "0x3fb950"
    yellow: "0xd29922"
    blue: "0x58a6ff"
    magenta: "0xbc8cff"
    cyan: "0x39c5cf"
    white: "0xb3b1ad"

  # Bright colors
  bright:
    black: "0x6e7681"
    red: "0xffa198"
    green: "0x56d364"
    yellow: "0xe3b341"
    blue: "0x79c0ff"
    magenta: "0xd2a8ff"
    cyan: "0x39c5cf"
    white: "0xb3b1ad"

  indexed_colors:
    - { index: 16, color: "0xd18616" }
    - { index: 17, color: "0xffa198" }

chalk: &chalk
  primary:
    background: "#151515"
    foreground: "#d0d0d0"
  cursor:
    text: "#151515"
    cursor: "#d0d0d0"
  normal:
    black: "#151515"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#d0d0d0"
  bright:
    black: "#505050"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#f5f5f5"

colors: *catpuccin
