# [[catpuccin.indexed_colors]]
# color = "0xF8BD96"
# index = 16
#
# [[catpuccin.indexed_colors]]
# color = "0xF5E0DC"
# index = 17
#
# [catpuccin.bright]
# black = "0x988BA2"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [catpuccin.cursor]
# cursor = "0xF5E0DC"
# text = "0x1E1D2F"
#
# [catpuccin.normal]
# black = "0x6E6C7E"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [catpuccin.primary]
# background = "0x1E1D2F"
# foreground = "0xD9E0EE"

# [chalk.bright]
# black = "#505050"
# blue = "#6fc2ef"
# cyan = "#12cfc0"
# green = "#acc267"
# magenta = "#e1a3ee"
# red = "#fb9fb1"
# white = "#f5f5f5"
# yellow = "#ddb26f"
#
# [chalk.cursor]
# cursor = "#d0d0d0"
# text = "#151515"
#
# [chalk.normal]
# black = "#151515"
# blue = "#6fc2ef"
# cyan = "#12cfc0"
# green = "#acc267"
# magenta = "#e1a3ee"
# red = "#fb9fb1"
# white = "#d0d0d0"
# yellow = "#ddb26f"
#
# [chalk.primary]
# background = "#151515"
# foreground = "#d0d0d0"

[colors.bright]
black = "#505050"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#f5f5f5"
yellow = "#ddb26f"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#d0d0d0"
yellow = "#ddb26f"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

# [[github.indexed_colors]]
# color = "0xd18616"
# index = 16
#
# [[github.indexed_colors]]
# color = "0xffa198"
# index = 17
#
# [github.bright]
# black = "0x6e7681"
# blue = "0x79c0ff"
# cyan = "0x39c5cf"
# green = "0x56d364"
# magenta = "0xd2a8ff"
# red = "0xffa198"
# white = "0xb3b1ad"
# yellow = "0xe3b341"
#
# [github.normal]
# black = "0x484f58"
# blue = "0x58a6ff"
# cyan = "0x39c5cf"
# green = "0x3fb950"
# magenta = "0xbc8cff"
# red = "0xff7b72"
# white = "0xb3b1ad"
# yellow = "0xd29922"
#
# [github.primary]
# background = "0x0d1117"
# foreground = "0xb3b1ad"

# [schemes.dark.bright]
# black = "#999999"
# blue = "#99ccff"
# cyan = "#99ffff"
# green = "#99ffcc"
# magenta = "#ff99cc"
# red = "#ff9999"
# white = "#ffffff"
# yellow = "#ffcc99"
#
# [schemes.dark.cursor]
# cursor = "#ffffff"
# text = "#000000"
#
# [schemes.dark.normal]
# black = "#666666"
# blue = "#6699cc"
# cyan = "#66cccc"
# green = "#66cc99"
# magenta = "#cc6699"
# red = "#cc6666"
# white = "#cccccc"
# yellow = "#cc9966"
#
# [schemes.dark.primary]
# background = "#000000"
# foreground = "#ffffff"
#
# [schemes.light.bright]
# black = "#a1a6b2"
# blue = "#0065ca"
# cyan = "#007693"
# green = "#007427"
# magenta = "#a03196"
# red = "#b22b31"
# white = "#282c36"
# yellow = "#715f00"
#
# [schemes.light.cursor]
# cursor = "#6d727e"
# text = "#fef9ec"
#
# [schemes.light.normal]
# black = "#c5c1b4"
# blue = "#208ffb"
# cyan = "#00a4c1"
# green = "#00a250"
# magenta = "#d160c4"
# red = "#e75c58"
# white = "#3e424d"
# yellow = "#a08a00"
#
# [schemes.light.primary]
# background = "#fef9ec"
# foreground = "#6d727e"
