schemes:
  light: &light
    primary:
      background: "#fef9ec"
      foreground: "#6d727e"
    cursor:
      text: "#fef9ec"
      cursor: "#6d727e"
    normal:
      black: "#c5c1b4"
      red: "#e75c58"
      green: "#00a250"
      yellow: "#a08a00"
      blue: "#208ffb"
      magenta: "#d160c4"
      cyan: "#00a4c1"
      white: "#3e424d"
    bright:
      black: "#a1a6b2"
      red: "#b22b31"
      green: "#007427"
      yellow: "#715f00"
      blue: "#0065ca"
      magenta: "#a03196"
      cyan: "#007693"
      white: "#282c36"
  dark: &dark # Default colors
    primary:
      background: "#000000"
      foreground: "#ffffff"
    cursor:
      text: "#000000"
      cursor: "#ffffff"
    normal:
      black: "#666666"
      red: "#cc6666"
      green: "#66cc99"
      yellow: "#cc9966"
      blue: "#6699cc"
      magenta: "#cc6699"
      cyan: "#66cccc"
      white: "#cccccc"
    bright:
      black: "#999999"
      red: "#ff9999"
      green: "#99ffcc"
      yellow: "#ffcc99"
      blue: "#99ccff"
      magenta: "#ff99cc"
      cyan: "#99ffff"
      white: "#ffffff"
colors: *dark
